name: Deploy Functions (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy-functions:
    name: Build and Deploy Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: reflat/backend/firebasefunctions/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: reflat/backend/firebasefunctions

      - name: Build
        run: npm run build
        working-directory: reflat/backend/firebasefunctions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          if [ -z "$FIREBASE_TOKEN" ] || [ -z "$PROJECT_ID" ]; then
            echo "FIREBASE_TOKEN and/or FIREBASE_PROJECT_ID secrets are not set" >&2
            exit 1
          fi
          firebase deploy --only functions --project "$PROJECT_ID" --non-interactive --token "$FIREBASE_TOKEN"
